name: dini_atlas
description: Dini Atlas
publish_to: 'none'
version: 1.0.6+11

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # splash
  flutter_native_splash: ^2.0.2
  
  # home widget
  app_widget: ^0.3.0

  # notifications
  android_alarm_manager_plus: ^3.0.4
  flutter_local_notifications: ^16.3.2

  # players
  audioplayers: ^5.2.1

  # network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0

  # image
  flutter_svg: ^2.0.9

  # database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  shared_preferences: ^2.2.2

  # helpers
  fpdart: ^1.1.0
  flutter_qiblah: ^2.2.1
  vibration: ^1.8.4
  intl: ^0.18.1
  path_provider: ^2.0.15
  sensors_plus: ^4.0.2
  share_plus: ^7.2.2
  url_launcher: ^6.2.3
  latlong2: ^0.9.0
  crypto: ^3.0.3
  app_settings: ^5.1.1
  sound_mode: ^3.0.0
  device_info_plus: ^9.1.2
  permission_handler: ^11.3.0

  # user
  in_app_review: ^2.0.8
  in_app_update: ^4.2.2
  feedback: ^3.0.0
  feedback_gitlab: ^3.0.0

  # architecture
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  
  # location
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  flutter_map: ^5.0.0

  # firebase
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  firebase_crashlytics: ^3.4.14
  firebase_analytics: ^10.8.6
  firebase_remote_config: ^4.3.13
  firebase_in_app_messaging: ^0.7.4+13

  # ads
  google_mobile_ads: ^4.0.0

  # in app purchase
  purchases_flutter: ^6.21.0
  webview_flutter: ^4.7.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.1
  stacked_generator: ^1.5.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/sounds/
    - assets/fonts/
    - assets/docs/
    - assets/docs/elifba/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Uthman
      fonts:
        - asset: assets/fonts/uthman.ttf
        - asset: assets/fonts/uthman_bold.ttf
          weight: 700