name: dini_atlas
description: Dini Atlas
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: ^3.0.4
  audioplayers: ^5.2.1
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  flutter_local_notifications: ^16.3.2
  flutter_native_splash: ^2.0.2
  flutter_qiblah: ^2.2.1
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  sensors_plus: ^4.0.2
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  url_launcher: ^6.2.3
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  vibration: ^1.8.4

dev_dependencies:
  build_runner: ^2.4.5
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  mockito: ^5.4.1
  stacked_generator: ^1.5.1

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700

    - family: Uthman
      fonts:
        - asset: assets/fonts/uthman.ttf
        - asset: assets/fonts/uthman_bold.ttf
          weight: 700