name: dini_atlas
description: Dini Atlas
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.3.0
  flutter_native_splash: ^2.0.2
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.0.15
  stacked: ^3.4.1+1
  stacked_services: ^1.3.0
  url_launcher: ^6.2.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.5.1
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/vectors/
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700